apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bigdata
data:
  PROJECT_HOME: /
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  ZOOKEPER_HOST: "zookeeper" 
  ZOOKEPER_PORT: "2181"
  SPARK_HOME: /spark
  KAFKA_HOST: "kafka" 
  KAFKA_PORT: "9092"
  WEB_SERVER_HOST: "webserver"
  WEB_SERVER_PORT: "5001"
  SPARK_MASTER_HOST: "1spark-master" 
  SPARK_MASTER_PORT: "8080"
  SPARK_WORKER_1_HOST: "spark-worker-1" 
  SPARK_WORKER_1_PORT: "8081"
  SPARK_WORKER_2_HOST: "spark-worker-2"
  SPARK_WORKER_2_PORT: "8081"
  SPARK_HISTORY_SERVER_HOST: "spark-history-server"
  SPARK_HISTORY_SERVER_PORT: "18081"

      